@startuml
skinparam classAttributeIconSize 0

interface javax.Servlet <<interface>> #aliceblue ##[dotted]blue {
+init()
+service()
+destory()
+getServletConfig()
+getServletInfo()
}

abstract javax.GenericServlet <<abstract>> #white {
+init()
+{abstract} service()
+destory()
+getServletConfig()
+getServletInfo()
}

class ConcreteServlet <<servlet>> #white {
+service()
}

hide fields

javax.Servlet <|.. javax.GenericServlet
javax.GenericServlet <|.. ConcreteServlet

@enduml